# Site Info
title:              "Spiritual pragmatism"
description:        "Nikita Chepanov's thoughts and opinions"
author_name:        "Nikita Chepanov" # change this to your name
logo_url:           /assets/chepanov-logo-1x1.svg

# Site Settings
url:                https://chepanov.com # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
